Removing extras
wolfi-dev/os pull request #12212
Opened 2024-02-01 01:33 UTC by johnfosborneiii

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2024-02-01 01:34 UTC, vaikas submitted a review, later dismissed

2024-02-01 06:53 UTC, imjasonh requested changes
Can you explain what this change is supposed to do? Is the current package wrong somehow?

You'll also need to bump the epoch to have this actually build a new package.

2024-02-01 18:39 UTC, johnfosborneiii commented
> Can you explain what this change is supposed to do? Is the current package wrong somehow?
> 
> You'll also need to bump the epoch to have this actually build a new package.

Yes, sorry it was in slack but I should've included in the PR (was burning the midnight oil)

Original lines of code removed packages from their out-of-the-box installation location, but the -DCMAKE_INSTALL_PREFIX flag that is being passed changes that location. This PR updates the extras to the intended location (and also fixes CVEs in the process)

2024-02-02 14:53 UTC, imjasonh approved these changes, later dismissed

2024-02-07 08:46 UTC, rawlingsj approved these changes, later dismissed

2024-04-10 14:39 UTC, johnfosborneiii commented
Already fixed in subsequent PR

2024-04-10 14:39 UTC, closed without merging