Add lcms2 pkg
wolfi-dev/os pull request #134
Opened 2022-11-25 23:13 UTC by tuananh

openjdk actually depends on lcms2 instead of lcms package. #55 

Signed-off-by: Tuan Anh Tran <me@tuananh.org>

2022-11-28 16:24 UTC, kaniini approved these changes

2022-11-28 16:25 UTC, kaniini commented on lcms2.yaml
> +      license: MIT GPL-3.0-only
This should be a valid SPDX license expression.

2022-11-28 16:26 UTC, kaniini commented on lcms2.yaml
> +  - runs: |
`uses: autoconf/configure`

2022-11-28 16:26 UTC, kaniini commented on lcms2.yaml
> +  - runs: |
`uses: autoconf/make-install`

2022-11-28 16:26 UTC, kaniini commented on lcms2.yaml
> +      make
`uses: autoconf/make`, drop `make check`

2022-11-28 16:27 UTC, kaniini requested changes
See above comments.

2022-11-29 16:07 UTC, kaniini approved these changes

2022-11-29 17:20 UTC, jdolitsky approved these changes

2022-11-29 17:21 UTC, merged