Rust bootstrap
wolfi-dev/os pull request #138
Opened 2022-11-29 15:58 UTC by Lunarequest

WIP rust bootstrap,
blocker: LLVM missing `/usr/bin/FileCheck`

2022-11-29 16:07 UTC, kaniini commented
`/usr/bin/FileCheck` is provided by `llvm15` package, but that doesn't get pulled in by `llvm15-dev` (which just pulls in the libraries).

2022-11-29 16:08 UTC, Lunarequest commented
ah, will add it

2022-11-29 16:32 UTC, Lunarequest commented
@kaniini any idea what provides `llvm-c/BitReader.h`?

2022-11-29 18:53 UTC, kaniini commented
rust probably needs to call the proper llvm-config binary ;/

2022-11-30 00:46 UTC, kaniini commented
llvm has to be rebuilt first, but i don't think that change is correct

2022-11-30 00:47 UTC, Lunarequest commented
> llvm has to be rebuilt first, but i don't think that change is correct

What would be the right change?

2022-11-30 02:31 UTC, tuananh commented on rust.yaml
> +        --llvm-root="/usr/lib/llvm15" \
use `--llvm-config` flag for specifying llvm-config bin path

https://github.com/rust-lang/rust/blob/2682b88c526d493edeb2d3f2df358f44db69b73f/src/bootstrap/configure.py#L98

2022-11-30 14:25 UTC, Lunarequest commented
I've got no idea why this is happening, any suggestions would be helpful

2022-11-30 14:45 UTC, kaniini commented
Not sure, can dig into it this morning.

2022-11-30 15:39 UTC, tuananh commented
> I've got no idea why this is happening, any suggestions would be helpful

i think the problem is with llvm-config still

BitReader.h should be included, when you run llmv-config --cxxflags

it should show something like below, and then that output will be passed to the build command c++


-I/usr/lib/llvm-15/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS

can you try doing llvm-config --cxxflags and see what it currently showing.

2022-12-01 00:26 UTC, Lunarequest commented
> can you try doing llvm-config --cxxflags and see what it currently showing.

cxxflags outputs the following
```
-I/usr/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```
cflags the following 
```
 -I/usr/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```

2022-12-01 01:29 UTC, Lunarequest commented
I fixed the build, I'm going to clean it up before I mark this as ready, I hope the following points can be agreed upon

- development utilities such as rustfmt or clippy won't be included(I don't believe we intend on people using wolfi for development so there's no need for these) 
- no docs(same as above)
- limited support for non-arch builds barring wasm(cross compiling to say aarch64 from x86_64 shouldn't be a thing once arch specific packages start being built. WASM however is an exception as there are use cases eg for javascript libraries)

2022-12-01 01:34 UTC, Lunarequest commented
looks like some minor fixes are needed, but it builds which is a lot more then before

2022-12-01 02:57 UTC, tuananh commented
> -I/usr/include

this is why it was failing in the first place i guess.

2022-12-05 07:30 UTC, Lunarequest commented
I've taken ill, could someone take over. The issue has to do with wasi-libc
https://github.com/rust-lang/rust/blob/897e37553bba8b42751c67658967889d11ecd120/src/bootstrap/compile.rs#L271-L280

2022-12-08 08:47 UTC, Lunarequest commented
this builds without wasm, I have no idea how to get wasm to build. If its needed I've got no idea how to get it to build

2022-12-08 08:51 UTC, Lunarequest commented
@kaniini since it was originally assigned to you, do you have any ideas how to get wasm to build?

2022-12-13 16:19 UTC, kaniini approved these changes

2022-12-13 16:19 UTC, kaniini requested changes, later dismissed

2022-12-13 16:19 UTC, kaniini commented on local-melange.rsa
> +-----BEGIN RSA PRIVATE KEY-----
Oh, this needs to be removed...

2022-12-13 16:19 UTC, kaniini commented on local-melange.rsa.pub
> +-----BEGIN PUBLIC KEY-----
As does this...

2022-12-13 21:41 UTC, patflynn commented
Just holding on merging until post-ARM boostrap. Should be no more than a few days.

2022-12-14 06:58 UTC, Lunarequest commented
There seems to be a issue with wget not the rust package :/

2022-12-27 22:04 UTC, dlorenc commented
Hey @Lunarequest - I got a copy of this branch rebased and fixed up over here: https://github.com/wolfi-dev/os/compare/main...dlorenc:os:rust-bootstrap?expand=1

It looks like the issue was the version constraint you had on rust-stage0. It might have been the wrong syntax (=< instead of >=), but also it was unnecessary. That triggered some bug somewhere which led to the busybox version of wget appearing, instead of the normal one, which led to the strange failure mode with dns-timeout.

I can send that one and shepherd it in (with your commits included), or feel free to grab my commit and move it over here!

2022-12-27 22:14 UTC, dlorenc commented
Looks right now - I think you just have to rebase to fix up the Makefile!

2022-12-27 22:19 UTC, dlorenc commented
Ah whoops, yeah I also had to remove tar. It comes in as part of one of the other packages.

2022-12-27 22:20 UTC, Lunarequest commented
Ahh will do.

2022-12-27 23:09 UTC, dlorenc commented
It's alive!!!

2022-12-27 23:10 UTC, dlorenc approved these changes

2022-12-27 23:33 UTC, imjasonh approved these changes

2022-12-27 23:45 UTC, merged