adds a patch to use sha256 instead of md5
wolfi-dev/os pull request #14041
Opened 2024-03-04 14:19 UTC by mritunjaysharma394

The existing upstream of opensearch-dashboard uses md5, this PR adds a patch to use more secure sha256 instead

2024-03-04 16:57 UTC, rawlingsj requested changes
This will change the expected default behaviour of opensearch dashboards, let's pause on merging this for now.

2024-03-04 20:42 UTC, xnox commented
@mritunjaysharma394 This looks great. Can you please submit this upstream? Or do you want me to do this? Cause if it is upstream, we don't need to maintain it ourselves downstream.

2024-03-05 12:33 UTC, mritunjaysharma394 commented
Created PR and an issue in upstream for this 

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6032
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6031

2024-03-26 22:21 UTC, xnox commented
See review & feedback upstream.

2024-03-26 22:21 UTC, closed without merging