wip: Add jre headless subpackage
wolfi-dev/os pull request #145
Opened 2022-12-01 00:20 UTC by tuananh

add jre-headless subpackage

2022-12-02 08:23 UTC, rawlingsj commented on openjdk-11.yaml
> +          export _TO_ROOT=${{targets.subpkgdir}}/usr/lib/jvm/openjdk
the JRE subpackage above is using jre in the folder path `/usr/lib/jvm/openjdk-jre` we should probably do the same here

2022-12-02 08:23 UTC, rawlingsj commented on Makefile
>  $(eval $(call build-package,openjdk-17,17.0.5.8-r2))
shall we do the same for java 17 to keep them consistent?

2022-12-13 21:42 UTC, rawlingsj commented
@tuananh thanks for the PR, were you able look look at some of the comments?  We'll look to merge soon!

2022-12-14 14:11 UTC, tuananh commented
> @tuananh thanks for the PR, were you able look look at some of the comments? We'll look to merge soon!

I'm gonna wrap this up this weekend

2022-12-20 16:46 UTC, luhring requested changes

2022-12-20 16:46 UTC, luhring commented on openjdk-17.yaml
> +    description: "Oracle OpenJDK 17 (JRE headless)"
Could you remove "Oracle" to stay consistent with the other package descriptions?

2022-12-28 14:55 UTC, luhring approved these changes

2022-12-28 15:01 UTC, imjasonh approved these changes

2022-12-28 15:01 UTC, merged