make stage0 usage more consistent
wolfi-dev/os pull request #1483
Opened 2023-04-20 15:28 UTC by imjasonh

This aligns usage of stage0 packages across the repo (hopefully correctly 🤞)

When `{package}` depends on itself, there is a `{package}-stage0.yaml` that builds that package from pre-built binaries and `provides: package-${{package.version}}-${{package.epoch}}` at an early version.

Then, when `{package}.yaml` has a dependency on itself, the first time it's built it will use the package `provides`ed by `{package}-stage0.yaml`, and subsequent versions will use the package `provides`ed by `{package}.yaml` _and not the `-stage0`_.

After `{package}` is successfully built, the intention is that the `stage0` packages are never depended on again, except when bootstrapping from scratch (e.g., a new architecture, or someone reproducing and checking our work).

The following packages are `stage0`'ed in this way:

- `go`
- `rust`
- `maven`
- `gradle`
- `sbt`

`openjdk-{11,17}` are not built this way, but should be. This PR adds `TODO`s.

@joshrwolf @rawlingsj @patflynn @deitch

2023-04-20 15:29 UTC, imjasonh commented on go-fips-1.20.yaml
> +      - go=1.20.999  # This should be go=${{package.version}}-${{package.epoch}}
This should be `go-fips=1.20.999` right?

2023-04-20 15:38 UTC, kaniini commented
I don't think `${{package.version}}` and friends are substituted in `provides` entries yet.

2023-04-20 16:07 UTC, imjasonh commented on go-fips-1.20.yaml
> +      - go=1.20.999  # This should be go=${{package.version}}-${{package.epoch}}
Did this.

2023-04-20 19:04 UTC, deitch commented
> I don't think ${{package.version}} and friends are substituted in provides entries yet.

They weren't, I was wondering about that when parsing `busybox-full.yaml`, so I pulled it in as a lib from melange for when building the graph.

2023-04-20 19:11 UTC, deitch commented
> Then, when {package}.yaml has a dependency on itself, the first time it's built it will use the package providesed by {package}-stage0.yaml, and subsequent versions will use the package providesed by {package}.yaml and not the -stage0.
>
> After {package} is successfully built, the intention is that the stage0 packages are never depended on again, except when bootstrapping from scratch (e.g., a new architecture, or someone reproducing and checking our work).

We had a bit of a discussion elsewhere on this, so it is good to centralize it.

As I understand this PR, the mechanism by which we indicate that something should depend on stage0 vs some prior build of the same package, is`provides`.

Let's say `a-1.3` depends on `a`; `a-stage0.yaml` (v1.0) provides `a=1.0`, so `a-1.3` can build depending on it. Now I have `a-1.3` in the repo. I modify `a.yaml` to get `a-1.4`. Now when I build, it still looks for `a`, but because it was already built, it find `a-1.3`, which is higher than stage0 (`a-1.0`), so it uses that?

If this is the case, then a few comments/questions:

* what happens when we rebuild from scratch? We now get `a-1.4` built based on `a-1.0`. That is not the same as `a-1.4` based on `a-1.3` which was based on `a-1.0`. Maybe we don't care, maybe we do, but that is not identical.
* If we ever actually have a need to reproduce from scratch, how do we do so?

2023-04-21 15:47 UTC, kaniini commented
I think we should not merge this, and wait for melange to support variable substitutions in `provide`.

2023-04-21 16:32 UTC, kaniini requested changes

2023-04-21 16:32 UTC, kaniini commented on sbt-stage0.yaml
> +      - sbt=1.8.2-r0
```suggestion
      - sbt=1.8.2
```

2023-04-21 16:33 UTC, kaniini approved these changes

2023-04-21 17:48 UTC, merged

2023-04-23 09:00 UTC, deitch commented
@imjasonh that does clarify. We are saying that what we need to be able to do is:

* rebuild any current yaml based on current state of the apk repository
* rebuild any current yaml from scratch, i.e. nothing in the apk repository

We accept that those two might not give identical results. Both will produce a package `a` whose version is 1.4, but they might not be binary identical. The first might be based on 1.3 based on 1.2 based on 1.0, some of which interim stages might not exist, while the latter will be based directly on 1.0, which is either here in the repo as `a-stage0` or upstream in bootstrap.

As long as we both accept that those two are our build requirements, and accept that the rebuilds could be different at a binary level, then we are fine here.

I think we should be able to rebuild at any point in direct reproduction of what was there, but that may very well be come with too much cost.