Multus-CNI
wolfi-dev/os pull request #15476
Opened 2024-03-19 19:40 UTC by sergio-chainguard

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2024-03-26 20:10 UTC, developer-guy commented on multus-cni.yaml
> +    CGO_ENABLED: "1"
is this required? is this binary should be dynamically linked?

2024-03-26 21:46 UTC, sergio-chainguard commented on multus-cni.yaml
> +      go-version: "1.21"
Awesome, thanks

2024-03-26 23:42 UTC, ajayk commented on multus-cni.yaml
> +      ls /usr/src/multus-cni/cmd
```suggestion
```

2024-03-26 23:49 UTC, ajayk commented on multus-cni.yaml
> +      go-version: "1.21"
```suggestion
```

2024-03-26 23:49 UTC, ajayk requested changes
Please add some basic tests

2024-03-27 15:43 UTC, ajayk approved these changes

2024-03-27 15:43 UTC, merged