new subpkg: add gator cli
wolfi-dev/os pull request #15773
Opened 2024-03-24 18:40 UTC by vanlongme

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2024-03-24 18:57 UTC, ajayk commented on gatekeeper-3.14.yaml
> +        - gatekeeper-compat=${{package.full-version}}
```suggestion
        - gatekeeper-gator=${{package.full-version}}
```

2024-03-25 04:04 UTC, vanlongme commented on gatekeeper-3.14.yaml
> +        - gatekeeper-compat=${{package.full-version}}
thanks @ajayk

2024-03-25 09:26 UTC, tuananh commented
@vanlongme update other version stream as well? we have gatekeeper-3.12, gatekeeper-3.13 & gatekeeper-3.14 here.

2024-03-26 09:12 UTC, vanlongme commented
> @vanlongme update other version stream as well? we have gatekeeper-3.12, gatekeeper-3.13 & gatekeeper-3.14 here.

3.12 and 3.13 have a lot of  CVEs, so I don't really want to keep track on it

2024-04-03 04:17 UTC, tuananh commented
@ajayk can you take a look at this?

2024-04-12 09:52 UTC, vanlongme commented
@ajayk Do you think that update action have some issue ?

2024-04-12 10:06 UTC, ajayk requested changes

2024-04-12 10:06 UTC, ajayk commented on gatekeeper-3.14.yaml
> +          cp bin/gator ${{targets.subpkgdir}}/gator
Can you use mv instead of cp and tests

2024-04-15 16:04 UTC, vanlongme commented on gatekeeper-3.14.yaml
> +          cp bin/gator ${{targets.subpkgdir}}/gator
I updated and tested on my machine.

2024-04-16 04:49 UTC, ajayk approved these changes

2024-04-16 04:50 UTC, merged

2024-04-16 10:10 UTC, tuananh commented
@ajayk looks like CI failure when uploading pkgs https://github.com/wolfi-dev/os/actions/runs/8700106538/job/23859816546