xcaddy: init at 0.3.5
wolfi-dev/os pull request #16050
Opened 2024-03-29 23:11 UTC by shyim

I can use then xcaddy in my own package to build a custom variant of caddy server with more modules

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [X] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [X] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2024-03-29 23:43 UTC, ajayk requested changes
Can you please add a basic test

2024-03-29 23:44 UTC, ajayk requested changes

2024-03-29 23:44 UTC, ajayk commented on xcaddy.yaml
> +  manual: false
```suggestion
```

2024-03-30 13:01 UTC, shyim commented
```
2024/03/30 12:42:58 INFO error during command execution: package kubebuilder: update found newer version 3.14.1 compared with package.version 3.14.0 in melange config
package jupyterhub-k8s-hub: update found newer version 3.3.6 compared with package.version 3.3.5 in melange config
```

should be fine

2024-03-30 13:14 UTC, ajayk approved these changes

2024-03-30 13:15 UTC, merged