cleanup php packages
wolfi-dev/os pull request #16125
Opened 2024-04-01 14:28 UTC by shyim

- Setup release monitoring for all packages which don't have it
- Remove pecl suffix from packages to have similar naming
- Updated package if available

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2024-04-01 14:28 UTC, shyim commented on php-8.1-http.yaml
> +      - php-8.1-pecl-http=${{package.full-version}}
Is that the correct way to rename a package?

2024-04-01 14:29 UTC, shyim commented on php-8.1-http.yaml
> +      - php-8.1-pecl-http=${{package.full-version}}
or do I create empty packages which have a runtime dependency on the new stuff?

2024-07-10 09:04 UTC, rawlingsj commented
thanks for the PR, I think we need to keep the package names as they are else this will break downstream consumers of these apks.  The additions of the release monitoring to the config blocks is great though, I wonder if you would mind creating a new PR with just those changes so we get automated updates for these packages?

2024-07-10 09:04 UTC, rawlingsj requested changes
thanks for the PR, I think we need to keep the package names as they are else this will break downstream consumers of these apks. The additions of the release monitoring to the config blocks is great though, I wonder if you would mind creating a new PR with just those changes so we get automated updates for these packages?

2024-12-09 23:42 UTC, mamccorm commented
Closing PR as theres been no initial loop backs since the first review, and all files have merge conflicts at this stage

2024-12-09 23:42 UTC, closed without merging