addon-resizer
wolfi-dev/os pull request #16701
Opened 2024-04-11 12:52 UTC by developer-guy

Note to the reviewer:
---

We also created an issue to the upstream project because there are different types of versioning scheme available so couldn't decide wihch one is the latest version flow but the most recent one was **1.8.20**, this is why we pick it up to move forward:

- https://github.com/kubernetes/autoscaler/issues/6702

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2024-04-11 15:39 UTC, dlorenc approved these changes

2024-04-11 15:40 UTC, dlorenc requested changes

2024-04-11 15:40 UTC, dlorenc commented on addon-resizer.yaml
> +
Can you add a basic test here?

2024-04-12 14:58 UTC, jamonation commented on addon-resizer.yaml
> +        pod_nanny -v
```suggestion
        pod_nanny -h
```

2024-04-12 14:58 UTC, jamonation commented on addon-resizer.yaml
> +        /pod_nanny -v
```suggestion
        /pod_nanny -h
```

2024-04-12 14:58 UTC, jamonation commented on addon-resizer.yaml
> +
```suggestion        
```

Fixes `yam` linting

2024-04-12 14:58 UTC, jamonation commented on addon-resizer.yaml
> +        /pod_nanny -v
-v is an error, but -h invokes the built in help

2024-04-12 18:26 UTC, jamonation approved these changes

2024-04-12 18:32 UTC, Dentrax approved these changes

2024-04-12 18:34 UTC, dlorenc approved these changes

2024-04-12 18:39 UTC, merged