neovim: fix msgpack build dependency
wolfi-dev/os pull request #17371
Opened 2024-04-21 12:44 UTC by pnasrat

Needs msgpack-c-dev after msgpack split in #5403

```
2024/04/21 12:35:03 WARN CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
2024/04/21 12:35:03 WARN   Could NOT find Msgpack (missing: MSGPACK_LIBRARY MSGPACK_INCLUDE_DIR)
2024/04/21 12:35:03 WARN   (Required is at least version "1.0.0")
2024/04/21 12:35:03 WARN Call Stack (most recent call first):
2024/04/21 12:35:03 WARN   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
2024/04/21 12:35:03 WARN   cmake/FindMsgpack.cmake:18 (find_package_handle_standard_args)
2024/04/21 12:35:03 WARN   src/nvim/CMakeLists.txt:23 (find_package)
2024/04/21 12:35:03 WARN
2024/04/21 12:35:03 WARN
2024/04/21 12:35:03 INFO -- Configuring incomplete, errors occurred!
2024/04/21 12:35:03 ERRO ERROR: failed to build package. the build environment has been preserved:
2024/04/21 12:35:03 INFO   workspace dir: /tmp/melange-workspace-3613637240
2024/04/21 12:35:03 INFO   guest dir: /tmp/melange-guest-4076264125
2024/04/21 12:35:03 INFO error during command execution: failed to build package: unable to run pipeline: exit status 1
make[1]: *** [Makefile:150: packages/aarch64/neovim-0.9.5-r0.apk] Error 1
make[1]: Leaving directory '/Users/pnasrat/workspace/src/github.com/wolfi-dev/os'
make: *** [Makefile:140: package/neovim] Error 2
```

### Pre-review Checklist

n/a

2024-04-21 12:45 UTC, pnasrat commented
Tested building in dev-container.

2024-04-21 16:31 UTC, ajayk requested changes
This needs epoch  bump 

```
package:
  name: neovim
  version: 0.9.5
  epoch: 0
  ``` 
  
  to 

```
package:
  name: neovim
  version: 0.9.5
  epoch:  1
```

2024-04-21 18:23 UTC, pnasrat commented
@ajayk have added epoch bump and pushed (squashed into prior commit)

2024-04-22 00:01 UTC, ajayk approved these changes

2024-04-22 00:01 UTC, merged