trurl.yaml: convert from fetch to git-checkout
wolfi-dev/os pull request #18345
Opened 2024-05-02 09:45 UTC by xnox

Convert trurl.yaml from fetch to git-checkout

2024-05-02 13:31 UTC, ajayk commented on trurl.yaml
> +      tag: trurl-0.10
seems we are building turl-0.10

2024-05-02 13:32 UTC, ajayk requested changes
Lets change it to build trurl-0.12

2024-05-02 17:43 UTC, xnox commented
@ajayk i agree but cannot approve.

2024-05-03 00:06 UTC, ajayk approved these changes

2024-05-03 10:32 UTC, rawlingsj approved these changes

2024-05-03 10:32 UTC, merged