split libva-glx
wolfi-dev/os pull request #18521
Opened 2024-05-03 21:17 UTC by lpcalisi

* uses meson pipelines
* split `libva-glx` like alpine

2024-05-07 12:46 UTC, lpcalisi commented
@xnox @imjasonh

2024-05-08 18:36 UTC, lpcalisi commented
@ajayk 🏓

2024-05-09 09:50 UTC, xnox commented
> `libva-glx` can not be compiled inside `libva` because a circular dependency with `mesa` (mesa needs libva for compilation and libva with glx needs mesa)
> 
> libva-glx and libva have the same source.
> 
> Do you think there is a better way to do this?

the breaking the bootstrap cycle like this is acceptable.
Note that `update:` section should use `github:` update tracker ideally (the lint check will point this out as well).

2024-05-13 14:06 UTC, mesaglio commented
can you help me with this too? @ajayk is another dependecy of opencv

2024-05-14 18:41 UTC, ajayk requested changes
Libva needs an epoch bump

2024-05-14 20:02 UTC, ajayk approved these changes, later dismissed
Looks good to me 
@xnox can you please take a look

2024-05-15 17:59 UTC, lpcalisi commented
@xnox shall we merge it?

2024-05-27 22:54 UTC, lpcalisi commented
@ajax could you approve workflows? i updated with the latest main changes

2024-06-01 15:45 UTC, lpcalisi commented
@ajayk could you re-run actions? scan cve was canceled

2024-12-05 03:07 UTC, mepi262 commented
@lpcalisi 
It seems that this pull request has conflicts.
Would you resolve it?

2025-04-24 12:49 UTC, closed without merging