git bootstrap
wolfi-dev/os pull request #18917
Opened 2024-05-09 12:30 UTC by xnox

- **git-bootstrap: add git with vendored curl**
    Ideally zlib-dev openssl-dev curl-dev and maybe even git-bootstrap
    should be in bootstrap-stage2/bootstrap-stage3. Until such time, add
    git-bootstrap in wolfi-dev/os which statically links against
    self-built dependencies. This enables using git-checkout to build any
    package in wolfi, including git itself. As git-bootstrap provides git
    that is installable and buildable using bootstrap-stage3 alone.
  

- **lz4.yaml: convert from fetch to git-checkout**
  

- **lz4.yaml: convert relese-monitor to github**

Previously submissions of lz4.yaml would error out, enable to resolve build cycle. See https://github.com/wolfi-dev/os/pull/18260

2024-05-09 12:42 UTC, xnox commented
> unresolvable cycle: zlib:1.3.1-r1@local -> libtool:2.4.7-r3@local, caused by: libtool:2.4.7-r3@local -> build-base:1-r7@local -> glibc-dev:2.39-r3@local -> glibc:2.39-r3@local -> zlib:1.3.1-r1@local

this is because "zlib-dev" is needed, whereas bootstrap only has "zlib" sigh.

and also likely bootstrap needs to add libtool, because otherwise it is pain.

2024-06-04 15:42 UTC, xnox commented
@smoser this enables to build key packages with git, including git itself.

2024-06-04 15:52 UTC, smoser commented
> @smoser this enables to build key packages with git, including git itself.

but how are you planning on using it?  I kind of feel like why would I not just use it for all the things (updating the pipeline to use git-bootstrap).

2024-06-04 16:02 UTC, xnox commented
> > @smoser this enables to build key packages with git, including git itself.
> 
> but how are you planning on using it? I kind of feel like why would I not just use it for all the things (updating the pipeline to use git-bootstrap).

because it is slower and doesn't support http2 and a few other things. and by default it provides git; but a lower priority. Thus it will be used if git doesn't exist; but stops being used once full git is built.

2024-06-05 15:06 UTC, smoser requested changes
one change but other than that looks great. thank you.

2024-06-05 15:06 UTC, smoser commented on git-bootstrap.yaml
> +        git config --list | grep 'user.email=wolf@wolfi.dev' || exit 1ist | grep 'user.email=test@example.com' || exit 1
`exit 1ist` and `exit 1config --list` ?

I see that you copied that, but it looks just like nonsense to me.

And , i see that @imjasonh fixed that test yesterday e1de9032301294948e48cd1897fe8b23778d83a4

So, please update to grab that change.

2024-06-18 10:45 UTC, smoser approved these changes

2024-06-18 10:46 UTC, merged