adds sonar-scanner-cli-entrypoint and compat packages
wolfi-dev/os pull request #21401
Opened 2024-06-05 18:37 UTC by mritunjaysharma394

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2024-06-06 23:52 UTC, jamonation commented on sonar-scanner-cli.yaml
> +          ln -s /usr/bin/sonar-scanner-cli "${{targets.subpkgdir}}"/opt/sonar-scanner/bin/
```suggestion
          ln -s /usr/bin/sonar-scanner-cli "${{targets.subpkgdir}}"/opt/sonar-scanner/bin/
          ln -s /usr/bin/sonar-scanner-cli "${{targets.subpkgdir}}"/opt/sonar-scanner/bin/sonar-scanner # entrypoint.sh script expects this

```

2024-06-06 23:53 UTC, jamonation commented on sonar-scanner-cli-entrypoint.yaml
> +  enabled: true
```suggestion
  manual: true
```

There's no obvious way with tags to automate updates.

2024-06-06 23:54 UTC, jamonation commented on sonar-scanner-cli-entrypoint.yaml
> +      extract: false
```suggestion
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SonarSource/sonar-scanner-cli-docker
      expected-commit: 8ee21641b014850a1c50d0635aa337bf9a6ba369
      tag: ${{package.version}}
```

2024-06-06 23:54 UTC, jamonation commented on sonar-scanner-cli-entrypoint.yaml
> +      cp entrypoint.sh ${{targets.destdir}}/usr/bin/
```suggestion
      install -m755 entrypoint.sh ${{targets.destdir}}/usr/bin/
```

2024-06-06 23:55 UTC, jamonation requested changes
Couple small changes and then this looks good

2024-06-07 15:09 UTC, jamonation commented on sonar-scanner-cli-entrypoint.yaml
> +      install -m755 entrypoint.sh ${{targets.destdir}}/usr/bin/
```suggestion
      install -m755 bin/entrypoint.sh ${{targets.destdir}}/usr/bin/
```

2024-06-07 15:26 UTC, jamonation commented on sonar-scanner-cli-entrypoint.yaml
> +  version: 10.0.3.1430_5.0.1
```suggestion
  version: "10.0.3.1430_5.0.1"
```

2024-06-07 20:29 UTC, jamonation requested changes
This should build!

2024-06-07 20:29 UTC, jamonation commented on sonar-scanner-cli-entrypoint.yaml
> +    to: mangled-package-version
```suggestion
```

2024-06-07 20:29 UTC, jamonation commented on sonar-scanner-cli-entrypoint.yaml
> +      tag: ${{vars.mangled-package-version}}
```suggestion
```

2024-06-07 20:32 UTC, jamonation commented on sonar-scanner-cli-entrypoint.yaml
> +# Fetches the sonar-scanner-cli entrypoint script used in the upstream docker image. We
```suggestion
#nolint:valid-pipeline-git-checkout-tag
# Fetches the sonar-scanner-cli entrypoint script used in the upstream docker image. We
```

2024-06-07 20:57 UTC, EyeCantCU approved these changes

2024-06-07 21:09 UTC, jamonation approved these changes

2024-06-07 21:09 UTC, merged