rename the k8s csi external snapshotter to match the other k8s csi pa…
wolfi-dev/os pull request #2246
Opened 2023-05-22 20:42 UTC by patflynn

2023-05-22 20:55 UTC, imjasonh requested changes
Let's update the subpackages too

2023-05-22 21:02 UTC, patflynn commented
done. should we get all the other instances of k8s-csi packages into this PR as well?

2023-05-22 21:21 UTC, imjasonh commented
Yeah anything else you think we should include

2023-05-23 06:59 UTC, developer-guy commented on packages.txt
> +kubernetes-csi-external-snapshotter
isn't it a duplicate entry 🤔

2023-05-23 18:22 UTC, patflynn commented
@imjasonh good to dismiss request changsed?

2023-05-23 18:22 UTC, imjasonh approved these changes

2023-05-23 18:23 UTC, developer-guy approved these changes

2023-05-23 18:24 UTC, developer-guy commented
eventually, we should rebuild the images as well to be able to use new package names, right? Will you do this @patflynn or I can do this for you WDYT?

2023-05-23 19:26 UTC, developer-guy commented
I'm going to work on the kubernetes-csi-external-snapshotter images for both public (latest) and private (6.0.1), I need this one to be merged first 😁

2023-05-23 19:35 UTC, merged

2023-05-23 20:53 UTC, Dentrax commented
Done! @patflynn

https://github.com/chainguard-images/images/pull/661