Add openssh-server test
wolfi-dev/os pull request #22951
Opened 2024-07-01 20:02 UTC by found-it

This is a follow-up to https://github.com/wolfi-dev/os/pull/22942

The old test _looked_ like it was testing `openssh-server` and it technically was. The test pipeline was tied to the `openssh` package though which means the `openssh` package was implicitly installed in the environment so the `sshd-session` binary was picked up. I took the same test and added it under the `openssh-server` subpackage so it gets tested without the extra packages.

2024-07-01 20:09 UTC, vaikas approved these changes

2024-07-01 21:35 UTC, hectorj2f approved these changes

2024-07-02 10:27 UTC, xnox requested changes
The test is now executed twice. And once with incorrect dependencies.

If we want to move sshd test to openssh-server subpackage test, i would expect to remove the top level test.

2024-07-02 19:46 UTC, found-it commented
@xnox I don't mind if it's executed twice. The top level `openssh` package includes `openssh-server` so keeping a test at the top level acts a sanity check that the `openssh` package also contains a working `sshd`. The cost of the test is cheap so I thought it more valuable to leave it

2024-07-02 21:30 UTC, xnox approved these changes

2024-07-02 21:30 UTC, merged