libreoffice: use build flags tested with ppt
wolfi-dev/os pull request #23733
Opened 2024-07-10 15:10 UTC by MthwRobinson

https://github.com/wolfi-dev/os/issues/22069 noted that `libreoffice` cannot convert PowerPoint files. We had the same issue and built `libreoffice` locally with the build flags in this PR. PowerPoint files convert successfully when building `libreoffice` with these flags.

Note, while this build works for our purposes (headless file conversion with `soffice`), I'm unsure if changing the flags would impact functionality other users may need.

Fixes:
- https://github.com/wolfi-dev/os/issues/22069

Related:

### Pre-review Checklist

After building the `.apk` locally with `melange`, we did the following to test.

```
docker run -it --platform linux/amd64 cgr.dev/chainguard/wolfi-base
```

```
apk add libreoffice-24-24.2.4.2-r1.apk  --allow-untrusted
ln -s /usr/lib/libreoffice/program/soffice.bin /usr/bin/libreoffice
ln -s /usr/lib/libreoffice/program/soffice.bin /usr/bin/soffice
chmod +x /usr/lib/libreoffice/program/soffice.bin
chmod +x /usr/bin/libreoffice
chmod +x /usr/bin/soffice
```

```
5288451bdb34:/app# soffice --headless --convert-to docx --outdir /app fake.doc
convert /app/fake.doc as a Writer document -> /app/fake.docx using filter : MS Word 2007 XML
5288451bdb34:/app# ls
fake-power-point.ppt            fake.docx
fake.doc                        libreoffice-24-24.2.4.2-r1.apk
5288451bdb34:/app# soffice --headless --convert-to pptx --outdir /app fake-power-point.ppt
convert /app/fake-power-point.ppt as a Impress document -> /app/fake-power-point.pptx using filter : Impress Office Open XML
5288451bdb34:/app# ls
fake-power-point.ppt            fake.doc                        libreoffice-24-24.2.4.2-r1.apk
fake-power-point.pptx           fake.docx
```

2024-07-10 15:45 UTC, dlorenc commented
Is there anyway you could provide a sample ppt file you used as a test along with a script you use to convert? You can just upload it here or something. Ideally we'll be able to narrow this down without having to disable all those features.

2024-07-10 18:29 UTC, MthwRobinson commented
@dlorenc - GitHub doesn't seem to let me attach `.ppt` or `.doc` files, but the docs to test are `fake.doc` and `fake-power-point.ppt` from this directory in or repo.

- https://github.com/Unstructured-IO/unstructured/tree/main/example-docs

2024-07-19 14:39 UTC, csbuild-c7ks7s commented
Hi! Any progress or updates on this PR?

2024-07-24 15:08 UTC, hughesadam87 commented
Is there any consensus if this fix is going in or not?  We rely on converting PPT to PDF and are gauging whether we should wait for this to go in, or go in another direction.

2024-08-05 15:40 UTC, EyeCantCU requested changes
I don't believe this is needed after some testing. This is how I set up a testing environment:

```
make local-wolfi
apk add libreoffice python-3.11 wget
wget https://github.com/Unstructured-IO/unstructured/raw/main/example-docs/fake-power-point.ppt -O /tmp/test.ppt
cd /tmp
```

Then I ran the above command:

```bash
/tmp# /usr/lib/libreoffice/program/soffice.bin --headless --convert-to pdf test.ppt
convert /tmp/test.ppt as a Impress document -> /tmp/test.pdf using filter : impress_pdf_Export
```

We can see from the log that it's able to successfully convert the PPT to a PDF. And I can see the created PDF, `test.pdf`, in the directory

Regardless, I don't believe we should be disabling all of these features. Interested in hearing how others are encountering this so that I can replicate this issue

2024-08-08 12:59 UTC, MthwRobinson commented
@EyeCantCU - Yeah I believe we can close this out. And I've heard from other users that PPT -> PPTX works with the current `libreoffice` build. Thanks!

2024-08-08 12:59 UTC, closed without merging