py3-attrs split out for versions add deps
wolfi-dev/os pull request #26489
Opened 2024-08-16 17:43 UTC by justinvreeland

This splits py3-attrs into multiple python3 versions and adds the hatch-fancy-pypi-readme package which is an attrs dep.

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [X] This PR is marked as fixing a pre-existing package request bug
  - [X] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [X] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [X] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [X] The upstream project actually supports multiple concurrent versions.
- [X] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [X] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)
- [ ] If non-streamed package names no longer built, open PR to withdraw them (see [WITHDRAWING PACKAGES](https://github.com/wolfi-dev/os/blob/main/WITHDRAWING_PACKAGES.md))

#### For package updates (renames) in the base images

When updating packages part of base images (i.e. cgr.dev/chainguard/wolfi-base or ghcr.io/wolfi-dev/sdk)
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk images successfully build
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk contain no obsolete (no longer built) packages
- [ ] Upon launch, does `apk upgrade --latest` successfully upgrades packages or performs no actions

2024-08-16 17:50 UTC, justinvreeland commented
> If non-streamed package names no longer built, open PR to withdraw them (see [WITHDRAWING PACKAGES](https://github.com/wolfi-dev/os/blob/main/WITHDRAWING_PACKAGES.md))

A package is still produced but it's empty not sure if I need to do anything here.


@pnasrat I can't assign people to PRs so tagging instead.

2024-08-16 21:06 UTC, pnasrat commented
@justinvreeland don't withdraw packages as the provider priority does the right thing.

Looks like the tests are failing

```
2024/08/16 17:54:06 INFO using python /usr/bin/python3.12
2024/08/16 17:54:06 WARN Traceback (most recent call last):
2024/08/16 17:54:06 WARN   File "<string>", line 1, in <module>
2024/08/16 17:54:06 WARN ModuleNotFoundError: No module named 'attrs'
2024/08/16 17:54:06 INFO /usr/bin/python3.12 -c "import attrs": FAIL
2024/08/16 17:54:06 INFO pod 
```

2024-08-16 21:08 UTC, pnasrat requested changes

2024-08-16 21:08 UTC, pnasrat commented on py3-attrs.yaml
> +          python${{range.key}} -m pip install --no-deps --no-build-isolation . --root=${{targets.contextdir}}
You don't' need to add a runtime pytho ndep

Don''t do manual install like this use

```
    dependencies:
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
```

2024-08-20 22:36 UTC, justinvreeland commented
Updated to match: https://github.com/wolfi-dev/os/pull/26761

2024-08-21 11:15 UTC, pnasrat requested changes

2024-08-21 11:15 UTC, pnasrat commented on py3-hatch-fancy-pypi-readme.yaml
This was merged in #26761 so this `py3-hatch-fancy-pypi-readme` can be dropped from the pr

2024-08-22 12:23 UTC, pnasrat requested changes
LGTM

2024-08-22 12:23 UTC, pnasrat commented on py3-attrs.yaml
> +      provides:
Are you missing

```
  runtime:
    - py${{range.key}}-importlib-metadata
```

2024-08-22 23:11 UTC, justinvreeland commented
@pnasrat 

That LGTM is marked as a requested change for some reason but I dont' seem to be able to resolve it, presumably because I haven't pushed a new version.

2024-08-23 11:48 UTC, pnasrat approved these changes
LGTM

2024-08-23 11:49 UTC, merged