Add sentencepiece package
wolfi-dev/os pull request #26675
Opened 2024-08-19 20:15 UTC by justinvreeland

Builds 4 packages 1 for each python3 version and the libraries.

New sentencepiece package

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [X] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [X] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

2024-08-19 20:15 UTC, justinvreeland commented
@pnasrat

2024-08-21 11:13 UTC, pnasrat requested changes, later dismissed

2024-08-21 11:13 UTC, pnasrat commented on sentencepiece.yaml
> +        - py3-${{vars.pypi-package}}
the `py3-${{vars.pypi-package}}` dependency looks incorrect

The py3-sentencepiece virtual should be handled by the provides below. You allso need to use provider-priority set to `${{range.value}}` for these subpackages.

2024-08-27 21:23 UTC, smoser requested changes
My only question here is why you named this 'sentancepiece' rather than 'py3-sentancepiece'.  setuptools is named 'py3-setuptools' but the "upstream name" (and name in pypi) is "setuptools".

Why differ here?

I'm only discussing consistency, not which is right or wrong.  we have ~ 525 py-* packages.

2024-08-28 12:37 UTC, justinvreeland commented
> My only question here is why you named this 'sentancepiece' rather than 'py3-sentancepiece'. setuptools is named 'py3-setuptools' but the "upstream name" (and name in pypi) is "setuptools".
> 
> Why differ here?

This was the first one I put up and I didn't really know how we were naming things. It should be named to match the others.

2024-08-28 13:19 UTC, smoser approved these changes

2024-08-28 13:23 UTC, merged