Update various python module provides
wolfi-dev/os pull request #26826
Opened 2024-08-21 16:27 UTC by justinvreeland

Fixes:
Missing dependency for multi version python3 subpackages

Related:

2024-08-21 16:33 UTC, smoser requested changes

2024-08-21 16:33 UTC, smoser commented on py3-click.yaml
> +        - python-${{range.key}}
you dont have to do this.
melange adds the correct depend here.  (which is actually `python-${{range.key}}-base`)

2024-08-23 13:49 UTC, smoser requested changes

2024-08-23 14:45 UTC, justinvreeland commented on py3-cloudpickle.yaml
>    description: Extended pickling support for Python objects
Nope, just missed it.

2024-08-26 12:33 UTC, smoser submitted a review, later dismissed
I'm just going to approve to land.  We can fix the python dep removal later.

2024-08-27 15:49 UTC, justinvreeland commented
@smoser think I'm still missing a review on this.

2024-08-27 19:00 UTC, smoser approved these changes

2024-08-27 19:03 UTC, xnox approved these changes

2024-08-27 19:03 UTC, merged