add thanos-operator
wolfi-dev/os pull request #2691
Opened 2023-06-08 22:36 UTC by developer-guy

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [x] REQUIRED - The package is added to `packages.txt`

#### For security-related PRs

- [ ] The security fix is recorded in `advisories` and `secfixes`

#### For version bump PRs

- [ ] The `epoch` field is reset to 0
- [ ] Patch source: _patch source here_

2023-06-08 22:53 UTC, jdolitsky submitted a review, later dismissed

2023-06-08 23:01 UTC, ajayk requested changes
Please add the CVE fixes for the package

2023-06-09 05:14 UTC, ajayk commented on thanos-operator.yaml
> +      go build -o bin/manager main.go
```Suggestion 
      # Address  CVE-2022-21698  GHSA-69ch-w2m2-3vjp  GHSA-69cg-p879-7622
      go get github.com/prometheus/client_golang@v1.11.1
      go get golang.org/x/text@v0.3.8
      go get golang.org/x/net@v0.7.0
      
      go build -o bin/manager main.go
```

2023-06-09 08:23 UTC, developer-guy commented on thanos-operator.yaml
> +      go build -o bin/manager main.go
thanks so much for this! I was also planning to do the same thing, but you beat me!

2023-06-09 08:59 UTC, rawlingsj commented on thanos-operator.yaml
> +update:
looks like the auto update CI check us failing as there are SDK releases on this repo.  You can ignore these and have the CI check go green using https://github.com/chainguard-dev/melange/blob/main/docs/UPDATE.md#ignore-versions

2023-06-09 09:04 UTC, developer-guy commented on thanos-operator.yaml
> +  - runs: |
cool, didn't know this pipeline supports deps option to fix CVEs, great!

2023-06-09 09:06 UTC, developer-guy commented on thanos-operator.yaml
> +update:
what should be the value of the `ignore-regex-patterns`? I couldn't understand what it should be :(

2023-06-14 20:38 UTC, ajayk approved these changes

2023-06-14 20:43 UTC, ajayk approved these changes

2023-06-14 20:47 UTC, merged