py3-meson-python: Multiversionize
wolfi-dev/os pull request #27194
Opened 2024-08-27 19:05 UTC by justinvreeland

2024-08-27 19:21 UTC, smoser requested changes

2024-08-27 19:21 UTC, smoser commented on py3-meson-python.yaml
Can you
1. move pipeline above subpackages (wierd that 'yam' didn't do that)
2. remove 'uses strip' since... this doesn't do aything at all.

2024-08-27 19:30 UTC, srishtih commented
Epoch needs to be bumped

2024-08-27 19:32 UTC, srishtih commented
Do we need to retain runtime packages for the main package?

2024-08-27 19:49 UTC, justinvreeland commented
You right I need to do both of those.

2024-08-28 16:03 UTC, srishtih commented
Epoch needs to be bumped

2024-08-29 13:04 UTC, smoser approved these changes
lgtm

2024-08-29 13:04 UTC, merged