add upx-v4.0.2: new package
wolfi-dev/os pull request #2922
Opened 2023-06-19 11:41 UTC by goproslowyo

Related: https://github.com/wolfi-dev/os/issues/2921

### Pre-review Checklist

#### For new package PRs only
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [x] REQUIRED - The package is added to `packages.txt`

I am opening this PR to add upx. Everything seems to build and package cleanly but I did notice that the program crashed when I tried to run it. Would appreciate some eyes on that to debug and push it over the line.

2023-06-19 12:41 UTC, rawlingsj requested changes, later dismissed
This looks great @goproslowyo!  Just a couple of nit comments.

2023-06-19 12:41 UTC, rawlingsj commented on upx.yaml
> +    #   - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
We can remove these comments, when building locally we can run
```
USE_CACHE=no MELANGE=melange make packages/upx  BUILDWORLD=no
```
which adds the repository and keyring using CLI flags

2023-06-19 12:42 UTC, rawlingsj commented
It could also do with a rebase to avoid the "branch out of date" warning above.

2023-06-21 07:15 UTC, goproslowyo commented
Thanks @rawlingsj  -- addressed those changes.

2023-06-23 00:17 UTC, goproslowyo commented
Hi @rawlingsj or @jdolitsky or @deitch  or @kaniini --Following up! This has been ready for a few days and I keep rebasing it to keep up to date with main but no one seems to be reviewing it.

2023-06-23 00:22 UTC, dlorenc commented
Sorry for the delay! Kicked off the tests.

2023-06-23 00:25 UTC, dlorenc commented
Looks like a few build/lint errors.

2023-06-23 00:44 UTC, goproslowyo commented
Great, taking a look, thanks!

2023-06-23 01:04 UTC, goproslowyo commented
Thakns! Looks like the `env` key was invalid -- removed and hopefully we're going for green now!

2023-06-23 16:34 UTC, dlorenc commented
Sorry this has been so painful - when you get your first PR merged the github actions won't need someone to approve anymore :(

2023-06-23 16:36 UTC, goproslowyo commented
> Sorry this has been so painful - when you get your first PR merged the github actions won't need someone to approve anymore :(

All good! More painful was the CI -- I think maybe build `yam` into the devcontainer or make it a git pre-hook or something so I knew beforehand :)

2023-06-23 16:56 UTC, dlorenc approved these changes

2023-06-23 16:56 UTC, dlorenc commented
Let's go!

2023-06-23 16:59 UTC, merged

2023-06-23 17:26 UTC, goproslowyo commented
Awesome! Thanks everyone excited to have contributed and looking forward to
more hopefully!

On Fri, Jun 23, 2023 at 9:59 AM dlorenc ***@***.***> wrote:

> Merged #2922 <https://github.com/wolfi-dev/os/pull/2922> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wolfi-dev/os/pull/2922#event-9619798766>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQKI22OOLCO2UW6B4FCQIGTXMXDP5ANCNFSM6AAAAAAZL2CASE>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-08-11 22:04 UTC, eddiezane commented
Hey @goproslowyo,

Thanks for this contribution! I'd like to send some swag your way. If interested could you please shoot an email to eddiezane at chainguard dot dev?