OpenJDK with crac enabled
wolfi-dev/os pull request #29728
Opened 2024-09-30 17:30 UTC by developer-guy

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)
- [ ] If non-streamed package names no longer built, open PR to withdraw them (see [WITHDRAWING PACKAGES](https://github.com/wolfi-dev/os/blob/main/WITHDRAWING_PACKAGES.md))

#### For package updates (renames) in the base images

When updating packages part of base images (i.e. cgr.dev/chainguard/wolfi-base or ghcr.io/wolfi-dev/sdk)
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk images successfully build
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk contain no obsolete (no longer built) packages
- [ ] Upon launch, does `apk upgrade --latest` successfully upgrades packages or performs no actions

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2024-09-30 17:42 UTC, xnox requested changes

2024-09-30 17:42 UTC, xnox commented on openjdk-crac-17.yaml
> +
I expect patched code to be build here. I.e. crac-17 branch or crac branch. As the tags seem to point at stock vanilla JDK.

2024-09-30 18:05 UTC, xnox commented
Note given it is a patchset we need to manage lifecycle of both openjdk and the crac patchset. As in have them separated somehow and apply / rebase as new openjdk get released.

2024-09-30 18:17 UTC, EyeCantCU commented on openjdk-crac-17.yaml
> +      - crac-criu
Let's remove this at buildtime and provide at runtime, create a symlink to jdk/lib/criu

2024-10-04 08:30 UTC, tuananh commented
subscribing 

Related issue: https://github.com/wolfi-dev/os/issues/27342

2024-10-09 12:21 UTC, closed without merging