chore(crac-criu): Use Canonical's fork, remove Python bindings
wolfi-dev/os pull request #29829
Opened 2024-10-01 20:24 UTC by EyeCantCU

This updates CRaC CRIU to track Canonical's fork instead of upstream

Additionally disable everything that isn't directly needed for OpenJDK CRaC, including Python bindings

2024-10-01 22:45 UTC, tuananh commented
related: https://github.com/wolfi-dev/os/issues/27342

@EyeCantCU may i ask how do we build a jdk image with crac support?

2024-10-01 23:06 UTC, EyeCantCU commented
@tuananh the build process for OpenJDK with CRaC support is inline with OpenJDK. The upstream repository can be found here: https://github.com/openjdk/crac

After that has been built, CRaC patched CRIU can be dropped into the `/path/to/jvm/installation/lib` folder

2024-10-02 07:28 UTC, philroche approved these changes
This seems like a big change. Can you link to a bug or provide context on why this change is being made?

2024-10-02 07:28 UTC, philroche requested changes
This seems like a big change. Can you link to a bug or provide context on why this change is being made?

2024-10-02 07:57 UTC, tuananh commented
> @tuananh the build process for OpenJDK with CRaC support is inline with OpenJDK. The upstream repository can be found here: https://github.com/openjdk/crac
> 
> After that has been built, CRaC patched CRIU can be dropped into the `/path/to/jvm/installation/lib` folder

do we have any plan to update openjdk here to add support for that?

2024-10-02 11:59 UTC, EyeCantCU commented
@philroche there is no issue tracking this, I've updated my PR description

@tuananh as upstream doesn't cut tags for the latest version of OpenJDK, this isn't something we plan to offer in Wolfi

2024-10-02 14:59 UTC, philroche approved these changes

2024-10-03 03:03 UTC, merged