kubernetes-1.31: Add kube-proxy-default-compat subpackage.
wolfi-dev/os pull request #29927
Opened 2024-10-02 17:18 UTC by wlynch

kube-proxy deployments assume the binary sits at
/usr/local/bin/kube-proxy (see
https://github.com/kubernetes/kubernetes/blob/a35bca903e24ea3cdbecb743c001b4c8f4db9e9c/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L79). This adds a compat package based off of kube-proxy-default which installs the binary at /usr/bin/kube-proxy.

Related: https://github.com/chainguard-dev/image-requests/issues/3667

2024-10-02 17:19 UTC, wlynch commented
cc @Aditvil-Dev - saw you were also looking at kube-proxy

2024-10-02 17:34 UTC, Aditvil-Dev commented
Need to bump CVEs. 
Also, can you make these changes across all enterprises packages as well.

2024-10-02 17:36 UTC, wlynch commented
yup! i'll get a enterprise PR open after this one

2024-10-02 17:50 UTC, Aditvil-Dev requested changes
- name: kube-proxy-compat-${{vars.kubernetes-version}} 
    dependencies:
      runtime:
        - kube-proxy-${{vars.kubernetes-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          # kube-proxy deployments usually use /usr/local/bin/kube-proxy
          # See https://github.com/kubernetes/kubernetes/blob/a35bca903e24ea3cdbecb743c001b4c8f4db9e9c/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L79
          ln -s usr/bin/kube-proxy ${{targets.subpkgdir}}/usr/local/bin/kube-proxy
    test:
      pipeline:
        - runs: stat /usr/local/bin/kube-proxy

2024-10-02 17:51 UTC, Aditvil-Dev commented
Can you also add that to the `kubernetes-${{vars.kubernetes-version}}-default` subpackage as well.

2024-10-04 15:38 UTC, wlynch commented
> name: kube-proxy-compat-${{vars.kubernetes-version}}

Done, though `${{range.key}}-${{vars.kubernetes-version}}-default` to match other package naming conventions.

> Can you also add that to the kubernetes-${{vars.kubernetes-version}}-default subpackage as well.

I don't think we want to? `kubernetes-${{vars.kubernetes-version}}-default` configures it's own set of symlinks in `/usr/bin`. This is specifically for kube-proxy where the common config defaults to `/usr/local/bin`.

I could maybe see making a `kubernetes-${{vars.kubernetes-version}}-default-compat` package if there are other components that need something similar. I know kube-apiserver does not, I don't know about the others.

2024-10-09 18:36 UTC, Aditvil-Dev commented
Reopend a new PR: https://github.com/wolfi-dev/os/pull/30447

2024-10-09 18:42 UTC, closed without merging