add chrony
wolfi-dev/os pull request #3020
Opened 2023-06-21 21:11 UTC by developer-guy

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [x] REQUIRED - The package is added to `packages.txt`

#### For security-related PRs

- [ ] The security fix is recorded in `advisories` and `secfixes`

#### For version bump PRs

- [ ] The `epoch` field is reset to 0
- [ ] Patch source: _patch source here_

2023-06-21 22:56 UTC, ajayk commented on chrony.yaml
> +# Generated from https://git.alpinelinux.org/aports/plain/main/libxshmfence/APKBUILD
probably reference to libxshmfence needs to be changed ?

2023-06-22 00:05 UTC, tuananh commented on chrony/chrony.pre-install
we dont need this hook i suppose?

2023-06-22 09:22 UTC, developer-guy commented on chrony/chrony.pre-install
we need this to create `chrony` user and group where we use `chown` command.

2023-06-22 15:39 UTC, developer-guy commented on chrony.yaml
> +      touch "${{targets.destdir}}"/var/lib/chrony/chrony.drift
I think we are not going to create an image for chrony as the Xage customer only requested for apk, [here](https://github.com/chainguard-dev/customer-issues/issues/429), @amdawson can correct me?

2023-06-22 21:16 UTC, imjasonh submitted a review, later dismissed

2023-06-22 21:20 UTC, kaniini requested changes

2023-06-22 21:20 UTC, kaniini commented on chrony.yaml
> +      ./chrony/chrony.pre-install
Why?  Define the `chrony` user as part of the build environment definition instead.

2023-06-22 21:25 UTC, kaniini approved these changes

2023-06-22 21:28 UTC, merged