exim: add subpackages, for lookups, scripts and utils.
wolfi-dev/os pull request #30647
Opened 2024-10-11 14:24 UTC by patdowney

This PR adds sub-packages that are present in the alpine package (https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/exim/APKBUILD) that weren't in the Wolfi package. Specifically it adds sub-packages for lookups (postgres, mysql and others) as well as packaging the `exim-utils` and `exim-scripts` too. 
Additionally, as also present in the alpine package, it adds a pre-install script to configure the `exim` user upon package installation.

Fixes:
* https://github.com/wolfi-dev/os/issues/29568

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [x] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

2024-10-17 14:49 UTC, willdeane commented
I've done some testing of this update as it fixes the issue I raised in https://github.com/wolfi-dev/os/issues/29568. I can confirm that the pgsql package works as expected. I've also checked that if you install the other lookup packages Exim does detect and load them on start-up, although I've not done any actual testing for the other lookup types:

```
/ # /usr/sbin/exim -bdf -d
Exim version 4.98 uid=0 gid=0 pid=104 D=f7715cfd
Support for: Content_Scanning crypteq Expand_dlfunc IPv6 move_frozen_messages OpenSSL TLS_resume DANE DKIM DNSSEC ESMTP_Limits ESMTP_Wellknown Event OCSP PIPECONNECT PRDR PROXY Queue_Ramp SPF TCP_Fast_Open
Lookups (built-in): lsearch wildlsearch nwildlsearch iplsearch dsearch passwd
Authenticators: cram_md5 dovecot plaintext spa tls
Routers: accept dnslookup ipliteral iplookup manualroute queryprogram redirect
Transports: appendfile/maildir autoreply lmtp pipe smtp
Malware: f-protd f-prot6d drweb aveserver fsecure kavdaemon sophie clamd mksd avast sock cmdline
Fixed never_users: 0
Configure owner: 0:0
Size of off_t: 8
Compiler: GCC [14.2.0]
Library version: Glibc: Compile: 2.40
                        Runtime: 2.40
Hints DB:
 Using tdb
Library version: OpenSSL: Compile: OpenSSL 3.3.2 3 Sep 2024
                          Runtime: OpenSSL 3.3.2 3 Sep 2024
                                 : built on: Tue Sep  3 16:14:00 2024 UTC
Library version: spf2: Compile: 1.2.11
                       Runtime: 1.2.11
Library version: PCRE2: Compile: 10.44
                        Runtime: 10.44 2024-06-07
Loading lookup modules from /usr/lib/exim/
Loaded "mysql.so" (1 lookup types)
Loaded "dnsdb.so" (1 lookup types)
Loaded "cdb.so" (1 lookup types)
Loaded "sqlite.so" (1 lookup types)
Loaded "dbmdb.so" (3 lookup types)
Loaded "pgsql.so" (1 lookup types)
Loaded 6 lookup modules
Total 16 lookups
Library version: CDB: Exim version 4.98
Library version: DBM: Exim version 4.98
Library version: DNSDB: Exim version 4.98
Library version: MySQL: Compile: 100808 10.8.8 [mariadb-10.8]
                        Runtime: 30401 3.4.1
                        Exim version 4.98
Library version: PostgreSQL: Exim version 4.98
Library version: SQLite: Compile: 3.45.1
                         Runtime: 3.45.1
                         Exim version 4.98

```

The pre-installs script to add the exim user and the addition of the Exim utility scripts are also very useful improvements.

2024-10-25 06:35 UTC, willdeane approved these changes
As per my comments earlier https://github.com/wolfi-dev/os/pull/30647#issuecomment-2419763668 I've done some testing of this and can confirm that this change fixes issue https://github.com/wolfi-dev/os/issues/29568 and adds improvements to add the exim user and the exim untils

2024-10-29 16:06 UTC, justinvreeland requested changes, later dismissed
At a first pass this all looks good except we'd rather not add new scriptlets. Would you mind removing the scriptlet that adds the user and groups.

2024-11-01 12:14 UTC, willdeane commented
The scriptlet to add the user is useful, at present Exim on wolfi won't start after install with first manually adding the user and group details, ideally installing the package would do the minimum setup needed for the service to run. There are other wolfi packages that have scriptlets with pre-install scripts, including postfix, which also setups users/groups and audit which setups required directories.

2024-11-08 12:21 UTC, patdowney commented
Sorry, have been away.  Let me do some research into how the `apko` process injects users for images (like it does for `nginx` and `envoy`) and integrate how that behaves into the exim build configuration

2024-11-08 14:14 UTC, patdowney commented
@justinvreeland - I've rebased / force-pushed to get rid of the extraneous commits to do with adding/removing the scriptlet. Unfortunately this means I can't resolve your requested change as the commit has disappeared, however I have removed the scriptlet since becoming more familiar with how `apko` makes use of these packages.

2024-11-12 19:10 UTC, justinvreeland commented on exim.yaml
>    accounts:
Is this still needed? I don't think I see it being referenced anywhere?

2024-11-14 17:47 UTC, justinvreeland approved these changes

2024-11-14 17:48 UTC, merged