new package: kots
wolfi-dev/os pull request #3081
Opened 2023-06-23 18:54 UTC by imjasonh

2023-06-23 19:39 UTC, denhamparry requested changes, later dismissed

2023-06-23 19:39 UTC, denhamparry commented on kots.yaml
> +  epoch: 2
Should the `epoch` be 0?

2023-06-23 19:50 UTC, imjasonh commented on kots.yaml
> +  epoch: 2
Yes indeed!

2023-06-25 03:10 UTC, ajayk approved these changes

2023-06-25 11:35 UTC, dlorenc approved these changes

2023-06-25 11:42 UTC, merged