add xmerl-1.3.32
wolfi-dev/os pull request #3102
Opened 2023-06-24 16:44 UTC by developer-guy

Signed-off-by: Batuhan Apaydin <batuhan.apaydin@chainguard.dev>

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [x] REQUIRED - The package is added to `packages.txt`

#### For security-related PRs

- [ ] The security fix is recorded in `advisories` and `secfixes`

#### For version bump PRs

- [ ] The `epoch` field is reset to 0
- [ ] Patch source: _patch source here_

2023-06-24 18:14 UTC, kaniini requested changes
The subpackage names need to describe their relationship to erlang.   Also the versions of the erlang applications should probably be omitted from the package name.

2023-06-25 12:51 UTC, developer-guy commented
> The subpackage names need to describe their relationship to erlang. 

So, we should add smth like "erlang-" prefix on front of them.

> Also the versions of the erlang applications should probably be omitted from the package name.

As we have erlang-25 (25.3.2.2-r0) and erlang-26 (26.0.1-r0) packages, so, I believe, they have both different version of the sub-packages, for example, for erlang-26 the sub-package xmerl* version is 1.3.2 but for erlang-25, it is 1.3.31.1, so, in that situtation, what should we do if we shouldn't provide the version information in the sub-package name? Thanks

2023-06-25 16:10 UTC, kaniini commented
We should use erlang-26-xmerl etc.

2023-06-26 12:38 UTC, imjasonh reviewed
This change lgtm but I'd like to wait for @kaniini's approval since she had comments.

2023-06-27 22:38 UTC, kaniini requested changes, later dismissed
Please flatten and use range instead of repeating the same block over and over again.

2023-06-27 22:38 UTC, kaniini commented on erlang-26.yaml
> +  - name: "erlang-26-xmerl"
Why not use range here?

2023-06-28 07:17 UTC, developer-guy commented on erlang-26.yaml
> +  - name: "erlang-26-xmerl"
great suggestion!

2023-06-29 15:16 UTC, imjasonh approved these changes

2023-06-29 16:16 UTC, merged