add aws-cli and its deps
wolfi-dev/os pull request #316
Opened 2022-12-28 09:43 UTC by tuananh

Signed-off-by: Tuan Anh Tran <me@tuananh.org>

2022-12-28 14:00 UTC, tuananh commented
im getting this issue when trying to build an image with this pkg

any pointer on why?

> Dec 28 13:57:03.126 [DEBUG] [arch:x86_64] [cmd:apk] [use-proot:false] [use-qemu:] ERROR: libffi-3.4.4-r0: trying to overwrite usr/share/info/dir owned by groff-1.22.3-r0.

2022-12-28 14:41 UTC, tuananh commented
i just look at a bunch of py3 packages and it seems wolfi is accepting downloading .whl files? i thought that's built files and wolfi prefer building from src?

2022-12-28 15:11 UTC, tuananh commented
i test by creating an image with apko. seems like all is good

![image](https://user-images.githubusercontent.com/627278/209832616-24b415ab-98f3-47dc-bc00-cafec2138658.png)

2022-12-29 13:35 UTC, dlorenc approved these changes, later dismissed

2023-01-03 18:01 UTC, tuananh commented
weird, i can build py3-yaml locally? any idea why it would break

2023-01-09 06:39 UTC, tuananh commented
```
2023/01/06 02:22:30 ERROR: failed to build package. the build environment has been preserved:
2023/01/06 02:22:30 melange (py3-asn1/x86_64):   workspace dir: /tmp/melange-workspace-270235846
2023/01/06 02:22:30 melange (py3-asn1/x86_64):   guest dir: /tmp/melange-guest-449109328
Error: failed to build package: unable to generate index: failed to parse package /home/runner/work/os/os/packages/x86_64/libxau-dev-1.0.10-r0.apk: expandApk(): expandApk error 5: expandApkWriter.Next error 5: open /tmp/734600351/stream-1.tar.gz: too many open files
2023/01/06 02:22:30 error during command execution: failed to build package: unable to generate index: failed to parse package /home/runner/work/os/os/packages/x86_64/libxau-dev-1.0.10-r0.apk: expandApk(): expandApk error 5: expandApkWriter.Next error 5: open /tmp/734600351/stream-1.tar.gz: too many open files
```

doesn't look related to this PR :-s

2023-01-09 22:12 UTC, luhring requested changes

2023-01-09 22:12 UTC, luhring commented on Makefile
> +$(eval $(call build-package,cython,0.29.32-r0))
There's already a line for cython

2023-01-09 22:12 UTC, luhring commented on Makefile
> +$(eval $(call build-package,yaml,0.2.5-r0))
There's already a line for yaml

2023-01-09 22:12 UTC, luhring commented on Makefile
> +$(eval $(call build-package,groff,1.22.3-r0))
There's already a line for groff

2023-01-13 00:30 UTC, luhring approved these changes

2023-01-13 00:59 UTC, kaniini approved these changes

2023-01-13 00:59 UTC, merged