New package libacvp
wolfi-dev/os pull request #31648
Opened 2024-10-23 12:16 UTC by xnox

A useful tool for testing OpenSSL against ACVP Demo server.

2024-10-23 15:37 UTC, smoser requested changes
Can you add test to execute `acvp_app`?

It looks like it has useful information in `--version`

```
# acvp_app  --version

 ACVP library version: libacvp_oss-2.1.2
ACVP protocol version: 1.0

 Compiled SSL version: OpenSSL 3.3.2 3 Sep 2024
   Linked SSL version: OpenSSL 3.3.2 3 Sep 2024

       FIPS requested: yes
FIPS Provider Version: (null)

# echo $?
1
```

not so helpfully it exits 1.

2024-10-23 15:54 UTC, xnox commented
> Can you add test to execute `acvp_app`?
> 
> It looks like it has useful information in `--version`
> 
> ```
> # acvp_app  --version
> 
>  ACVP library version: libacvp_oss-2.1.2
> ACVP protocol version: 1.0
> 
>  Compiled SSL version: OpenSSL 3.3.2 3 Sep 2024
>    Linked SSL version: OpenSSL 3.3.2 3 Sep 2024
> 
>        FIPS requested: yes
> FIPS Provider Version: (null)
> 
> # echo $?
> 1
> ```
> 
> not so helpfully it exits 1.

i guess i can propose this package to enterprise-packages and then test will pass, as i will be able to depend on a fips module in the test.

2024-10-23 19:48 UTC, xnox commented
even with fips provider it exists 1, lol =) so will structure a tight test for this.

2024-11-01 17:35 UTC, smoser approved these changes
this is good.  some update version will fix --version to exit 0.
that update PR will fail and someone will change this to accomodate.
thanks.

2024-11-01 17:35 UTC, smoser commented on libacvp.yaml
> +        ! acvp_app --version >version.output
I like it. thank you.

2024-11-01 17:36 UTC, merged