add orc
wolfi-dev/os pull request #3178
Opened 2023-06-28 20:36 UTC by developer-guy

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [x] REQUIRED - The package is added to `packages.txt`

#### For security-related PRs

- [ ] The security fix is recorded in `advisories` and `secfixes`

#### For version bump PRs

- [ ] The `epoch` field is reset to 0
- [ ] Patch source: _patch source here_

2023-06-28 20:53 UTC, kaniini requested changes

2023-06-28 20:53 UTC, kaniini commented on orc.yaml
> +    dependencies:
The -dev packages should discover their dependencies using SCA since Melange 0.3 release.  We should not need these blocks anymore.

2023-06-29 01:11 UTC, dlorenc approved these changes

2023-06-29 07:25 UTC, kaniini approved these changes

2023-06-29 07:28 UTC, merged