New Package: pgadmin4(most popular and feature rich Open Source admin…
wolfi-dev/os pull request #37339
Opened 2024-12-17 22:11 UTC by Aditvil-Dev

…istration and development platform for PostgreSQL)

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)
- [ ] If non-streamed package names no longer built, open PR to withdraw them (see [WITHDRAWING PACKAGES](https://github.com/wolfi-dev/os/blob/main/WITHDRAWING_PACKAGES.md))

#### For package updates (renames) in the base images

When updating packages part of base images (i.e. cgr.dev/chainguard/wolfi-base or ghcr.io/wolfi-dev/sdk)
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk images successfully build
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk contain no obsolete (no longer built) packages
- [ ] Upon launch, does `apk upgrade --latest` successfully upgrades packages or performs no actions

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2025-01-08 16:05 UTC, Aditvil-Dev commented
Advisories filed: https://github.com/wolfi-dev/advisories/pull/11225

2025-01-08 20:29 UTC, EyeCantCU requested changes

2025-01-08 20:29 UTC, EyeCantCU commented on pgadmin4-17.yaml
> +        - py3-pip
We pin Python 3 above, this should be pinned too

2025-01-08 20:29 UTC, EyeCantCU commented on pgadmin4-17.yaml
> +        python3 /pgadmin4/web/pgAdmin4.py &  # Start pgAdmin4 in background
We have a test pipeline for daemons we can use here

2025-01-08 20:29 UTC, EyeCantCU commented on pgadmin4-17.yaml
> +        source venv/bin/activate
We should expect our package to work without sourcing the virtual environment. We should set PYTHONPATH or run the binaries (really scripts) in the bin folder pointing to the vendored Python install

2025-01-08 20:29 UTC, EyeCantCU commented on pgadmin4-17.yaml
> +      - gcc
Pulled in by build-base

2025-01-08 20:29 UTC, EyeCantCU commented on pgadmin4-17.yaml
> +    tag-filter: REL-8
`REL-`, if they move to 9 we won't get updates

2025-01-09 17:06 UTC, stevebeattie commented on pgadmin4-17.yaml
> +      cp ./pkg/docker/entrypoint.sh ${{targets.destdir}}/entrypoint.sh
Is there a particular reason for installing into `/pgadmin4` and `/entrypoint.sh` rather than something like `/usr/share/pgadmin4`, `/usr/bin`?

2025-01-10 01:17 UTC, stevebeattie commented on pgadmin4-17.yaml
> +      cp ./pkg/docker/entrypoint.sh ${{targets.destdir}}/entrypoint.sh
Ah, okay, thanks!

2025-01-12 03:18 UTC, EyeCantCU requested changes

2025-01-12 03:18 UTC, EyeCantCU commented on pgadmin4-17.yaml
> +        - postgresql-${{vars.pg-version}}-dev
We shouldn't need PostgreSQL dev in tests

2025-01-12 15:31 UTC, Aditvil-Dev commented on pgadmin4-17.yaml
> +        - postgresql-${{vars.pg-version}}-dev
Without `-dev` it fails to recognise `initdb` command.
```
2025/01/12 10:28:53 WARN + cd /home/build
2025/01/12 10:28:53 WARN + useradd wolfi
2025/01/12 10:28:53 WARN + sudo -u wolfi initdb -D /tmp/test_db
2025/01/12 10:28:53 WARN sudo-rs: 'initdb': command not found
```

2025-01-12 15:47 UTC, tuananh commented on pgadmin4-17.yaml
> +        - postgresql-${{vars.pg-version}}-dev
`-client` package should be brought in if you need `initdb` i think. 

dev works because it requires client subpkg.

2025-01-13 19:42 UTC, EyeCantCU approved these changes

2025-01-13 20:19 UTC, merged