Add python3 as a dep so g-ir-scanner can run
wolfi-dev/os pull request #37370
Opened 2024-12-17 23:34 UTC by murraybd

g-ir-scanner would previously fail to run because python3 was not available.

2024-12-17 23:56 UTC, smoser requested changes
This isn't right. We need to fix the shbang so it uses the Python that it was installed for. 

A python3 drop will Get you a /usr/bbin/python3, but not necessarily the right python3. 

See my issue for unversioned Python and 313. Also related here is the python-as wrapper, it works likely fix this.

2024-12-18 00:05 UTC, dannf commented
For reference, here's the issue @smoser is referring to - https://github.com/wolfi-dev/os/issues/37197
According to that, I think we want to try to use the suggestion in the "pick a specific version" example, and then fallback to the `python-as-wrapper` thing if it fails to inherit a python3.13 shbang.

2024-12-18 01:43 UTC, smoser commented
> For reference, here's the issue @smoser is referring to - https://github.com/wolfi-dev/os/issues/37197
> 
> According to that, I think we want to try to use the suggestion in the "pick a specific version" example, and then fallback to the `python-as-wrapper` thing if it fails to inherit a python3.13 shbang.

If we land Python-as-wrapper (#36891) we can use that. I do think it's useful to generally "do the right thing".

2024-12-18 01:43 UTC, smoser commented
> For reference, here's the issue @smoser is referring to - https://github.com/wolfi-dev/os/issues/37197
> 
> According to that, I think we want to try to use the suggestion in the "pick a specific version" example, and then fallback to the `python-as-wrapper` thing if it fails to inherit a python3.13 shbang.

If we land Python-as-wrapper (#36891) we can use that. I do think it's useful to generally "do the right thing".

2024-12-18 20:23 UTC, murraybd commented
I'm going to close this in favor of sil2100's PR at https://github.com/wolfi-dev/os/pull/37393.

2024-12-18 20:23 UTC, closed without merging