wip: add tensorflow-cpu
wolfi-dev/os pull request #37597
Opened 2024-12-19 13:11 UTC by maxgio92

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)
- [ ] If non-streamed package names no longer built, open PR to withdraw them (see [WITHDRAWING PACKAGES](https://github.com/wolfi-dev/os/blob/main/WITHDRAWING_PACKAGES.md))

#### For package updates (renames) in the base images

When updating packages part of base images (i.e. cgr.dev/chainguard/wolfi-base or ghcr.io/wolfi-dev/sdk)
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk images successfully build
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk contain no obsolete (no longer built) packages
- [ ] Upon launch, does `apk upgrade --latest` successfully upgrades packages or performs no actions

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2024-12-21 10:31 UTC, developer-guy commented on tensorflow-cpu.yaml
> +  epoch: 1
epoch should be zero here 🫠

2025-01-07 16:06 UTC, anushkamittal20 commented on tensorflow-cpu.yaml
> +        - curl
shouldnt we get curl in runtime dep : https://github.com/tensorflow/build/blob/master/tensorflow_runtime_dockerfiles/cpu.packages.txt

2025-01-07 17:16 UTC, maxgio92 commented on tensorflow-cpu.yaml
> +        - curl
Right, good catch

2025-01-08 07:15 UTC, anushkamittal20 commented on tensorflow-cpu.yaml
> +        - curl
Do we need this here if we have it as a runtime dep 🤔 

P.S. Please correct me if I got that wrong!

2025-01-08 10:02 UTC, maxgio92 commented on tensorflow-cpu.yaml
> +        - curl
It's needed for the tests for Jupyter

2025-01-08 10:33 UTC, anushkamittal20 commented
This PR looks good to me! Probably just needs a version bump.

2025-01-08 21:28 UTC, EyeCantCU requested changes

2025-01-08 21:28 UTC, EyeCantCU commented on tensorflow-cpu.yaml
> +          pip${{vars.py-version}} install \
Instead of installing directly to site packages, we'll need to install to a virtual environment

2025-01-08 21:28 UTC, EyeCantCU commented on tensorflow-cpu.yaml
I'd set `package.options.no-provides` and `no-depends` to `true` as we're bundling several packages together

2025-01-08 21:28 UTC, EyeCantCU commented on tensorflow-cpu.yaml
> +      - python-${{vars.py-version}}-dev
Is it intentional to ship the dev variant of Python?

2025-01-08 21:28 UTC, EyeCantCU commented on tensorflow-cpu.yaml
> +  py-version: 3.11
I'm sure there's a reason, but why do we pin to 3.11?

2025-01-08 21:28 UTC, EyeCantCU commented on tensorflow-cpu.yaml
> +        jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root >/dev/null 2>&1 &
We have a pipeline for daemons we could reuse here, something like `test/daemon-check-output`

2025-01-08 21:28 UTC, EyeCantCU commented on tensorflow-cpu.yaml
> +    - runs: python${{vars.py-version}} -m pip --version
This looks safe to remove

2025-01-08 21:28 UTC, EyeCantCU commented on tensorflow-cpu.yaml
> +    - name: Test Tensorflow library
This is great!

2025-01-09 07:46 UTC, maxgio92 commented on tensorflow-cpu.yaml
> +    - runs: python${{vars.py-version}} -m pip --version
Oh yeah!

2025-01-09 09:17 UTC, maxgio92 commented on tensorflow-cpu.yaml
> +      - python-${{vars.py-version}}-dev
Yep, I just stuck to what upstream does ([here](https://github.com/tensorflow/build/blob/35a7dbc754193523e5582ce5b5cbbb4c07cff7b2/tensorflow_runtime_dockerfiles/setup.python.sh#L31)). Do you think it's only needed at build time for the next pip-installs?

2025-01-10 11:25 UTC, maxgio92 commented on tensorflow-cpu.yaml
> +  py-version: 3.11
Also, it seems that 3.12 is not officially supported in their build setups (for which the [issue](https://github.com/tensorflow/build/issues/210)), even though I'm not sure it's an hard requirement.

2025-01-10 11:59 UTC, maxgio92 commented on tensorflow-cpu.yaml
> +  py-version: 3.11
I just added a check that will fail the build when we're using a different version from the default one supported by upstream, referencing their Dockerfile's ARG.

2025-01-10 19:00 UTC, EyeCantCU commented on tensorflow-cpu.yaml
> +      - python-${{vars.py-version}}-dev
@maxgio92 I'm honestly unsure. Could we test with the non-dev variant?

2025-01-10 19:00 UTC, EyeCantCU commented on tensorflow-cpu.yaml
> +  py-version: 3.11
Awesome!

2025-01-10 19:53 UTC, maxgio92 commented on tensorflow-cpu.yaml
> +      - python-${{vars.py-version}}-dev
Sure @EyeCantCU. Tests and build seem to pass even without that 🤔

2025-01-10 23:20 UTC, EyeCantCU commented on tensorflow-cpu.yaml
> +      - python-${{vars.py-version}}-dev
Let's send it and come back if problematic

2025-01-13 14:59 UTC, EyeCantCU approved these changes

2025-01-13 15:00 UTC, merged