systemd: Add misc dependencies for additional functionality
wolfi-dev/os pull request #37794
Opened 2024-12-19 23:02 UTC by justinvreeland

Also runs the upstream tests with some skips that don't work primarily due to the runtime env and explicitly build for release.

Also add tpm2-tss to build the systemd related pieces.

2024-12-19 23:12 UTC, justinvreeland commented
```
❌ aarch64/systemd-test-257.1-r0.apk

usr/lib/systemd/tests/testdata/units/TEST-07-PID1.main-PID-change.sh (CRITICAL)

References
```
Seems reasonable to flag. I can drop the package or that particular file if need be but it's nice to have the tests.

2025-01-07 09:22 UTC, 89luca89 requested changes

2025-01-07 16:31 UTC, justinvreeland commented on systemd.yaml
> +            # Skipping tests:
Happy to do that but I'm not sure which ones is the the filling arm test they all seem pretty generic to me.

2025-01-07 18:22 UTC, justinvreeland commented on systemd.yaml
> +            # Skipping tests:
Sure but which one is the failing ARM test? they all seem architecture agnostic to me.

2025-01-08 19:12 UTC, justinvreeland commented on systemd.yaml
> +            # Skipping tests:
@89luca89  Were you thinking of the comment I had above: https://github.com/wolfi-dev/os/pull/37794#issuecomment-2555933004

That's the malcontent error not a test failure nothing needs to be fixed for it.

2025-01-09 13:51 UTC, 89luca89 approved these changes

2025-01-09 16:45 UTC, merged

2025-01-09 17:59 UTC, xnox reviewed
nice!