new package: pre-commit
wolfi-dev/os pull request #38502
Opened 2024-12-30 13:37 UTC by sanjayk0508

Related: #35978 

![Screenshot (376)](https://github.com/user-attachments/assets/11dd6b49-d70f-4392-a3a2-94982b30c057)

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [x] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)
- [ ] If non-streamed package names no longer built, open PR to withdraw them (see [WITHDRAWING PACKAGES](https://github.com/wolfi-dev/os/blob/main/WITHDRAWING_PACKAGES.md))

#### For package updates (renames) in the base images

When updating packages part of base images (i.e. cgr.dev/chainguard/wolfi-base or ghcr.io/wolfi-dev/sdk)
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk images successfully build
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk contain no obsolete (no longer built) packages
- [ ] Upon launch, does `apk upgrade --latest` successfully upgrades packages or performs no actions

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2025-01-05 19:33 UTC, mamccorm requested changes
Thanks - left some suggestions, tests are also failing and pre-commit has a dependency on cfgv which would need to be available. cfgv also seems to require additional dependencies.

If your not planning on continuing down this path, appreciate if you can close the PR, otherwise will re-review once you've had a chance to dig in

2025-01-05 19:33 UTC, mamccorm commented on pre-commit.yaml
> +      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
These can be removed as we default to these values in wolfi:

```suggestion
```

2025-01-05 19:33 UTC, mamccorm commented on pre-commit.yaml
> +      tag: v4.0.1
This was hard-coded, will need to be dynamically updated along with the package version:

```suggestion
      tag: v${{package.version}}
```

2025-01-05 19:33 UTC, mamccorm commented on pre-commit.yaml
> +        from pre_commit.main import main
The tests are failing:

```bash
% make test/pre-commit
2025/01/05 19:17:58 INFO running step "python/import"
2025/01/05 19:17:58 WARN + '[' -d /home/build ]
2025/01/05 19:17:58 WARN + cd /home/build
2025/01/05 19:17:58 WARN + exit 0
2025/01/05 19:17:58 WARN + '[' -d /home/build ]
2025/01/05 19:17:58 WARN + cd /home/build
2025/01/05 19:17:58 WARN + set +x
2025/01/05 19:17:58 INFO using python /usr/bin/python3.13
2025/01/05 19:17:58 INFO No package specified for import.
```


```suggestion
test:
  pipeline:
    - uses: python/import
      with:
        import: pre_commit

    - name: Basic command tests
      runs: |
        pre-commit --version | grep -q "${{package.version}}"
        pre-commit --help | grep -q "usage:"
```

Also, tests failing as pre-commit looks to need 'cfgv', which isn't packaged. Tried hacking in 'pip install cfgv' and theres other issues with missing deps. This will need more work and isn't workable in its current state

2025-01-15 13:16 UTC, sanjayk0508 commented on pre-commit.yaml
> +        from pre_commit.main import main
i’ve also packaged [cfgv](https://github.com/asottile/cfgv) and tested it locally. would you recommend pushing the py3-cfgv package before proceeding with testing the pre-commit package import?

2025-01-20 06:32 UTC, closed without merging