Bind tools dependencies part4 .....
wolfi-dev/os pull request #423
Opened 2023-01-11 21:37 UTC by rawlingsj

This PR includes an unusually large number of packages that relate to eventually building bind-tools.  Rather than split into a PR for each which makes it hard to manage CI, we're trying a single PR with multiple commits that should help the review process.

This PR includes `docbook-xml` and `docbook-xsl` which means we can recompile `xmlto` and `glib` as it was missing from each when originally added.

Packages being added:

- swig
- lua 5.4
- graphviz
- vala
- libgcrypt
- libsecret
- libtasn1
- strace
- wayland
- wayland-protocols
- at-spi2-core
- py3-docutils
- py3-pygments
- docbook-xml
- docbook-xsl
- rarian
- itstool
- shared-mime-info

2023-01-11 22:33 UTC, kaniini commented
CI and lint are failing atm

2023-01-12 02:09 UTC, tuananh commented
i'm surprised to see wayland here. do we need it in container workload?

2023-01-12 09:01 UTC, rawlingsj commented
AFAICT it's just used as a dependency to compile other packages, needed to eventually compile bind-tools.

2023-01-12 18:33 UTC, kaniini requested changes

2023-01-12 18:33 UTC, kaniini commented on docbook-xml.yaml
> +      #!/bin/busybox sh
Instead of having a scriptlet here, lets merge docbook-xml and docbook-xsl into a single package and then build /etc/xml/catalog at build time.

2023-01-13 17:24 UTC, kaniini approved these changes

2023-01-13 17:25 UTC, merged