Add pulsar and py3-pulsar clients.
wolfi-dev/os pull request #4898
Opened 2023-08-29 01:29 UTC by dlorenc

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [X] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [X] REQUIRED - The version of the package is still receiving security updates

2023-08-29 02:43 UTC, ajayk requested changes
googletest is already present on wolfi as https://github.com/wolfi-dev/os/blob/main/gtest.yaml

2023-08-29 02:53 UTC, kaniini requested changes, later dismissed
This is vendoring pybind11, which is already packaged as `py3-pybind11`.

2023-08-29 17:21 UTC, dlorenc commented
> This is vendoring pybind11, which is already packaged as `py3-pybind11`.

Should be good now!

2023-08-31 20:32 UTC, ajayk approved these changes

2023-08-31 20:59 UTC, merged