feat: add snappy pkg
wolfi-dev/os pull request #498
Opened 2023-01-30 08:06 UTC by tuananh

Signed-off-by: Tuan Anh Tran <me@tuananh.org>

2023-01-30 13:48 UTC, kaniini requested changes, later dismissed

2023-01-30 13:48 UTC, kaniini commented on snappy.yaml
> +      - runs: |
`- uses: split/static`

2023-01-30 17:13 UTC, jdolitsky approved these changes

2023-01-31 15:42 UTC, rawlingsj approved these changes

2023-02-02 21:07 UTC, merged