Fluentd plugin for http-out
wolfi-dev/os pull request #5571
Opened 2023-09-14 19:46 UTC by cjohannsen81

Attempt to add ruby gem for fluentd to enable http out traffic for /metrics

Fixes: https://github.com/chainguard-dev/customer-issues/issues/564

Related: https://chainguardhelp.zendesk.com/agent/tickets/191

### Pre-review Checklist

#### For version bump PRs

- [X] The `epoch` field is reset to 0

2023-09-14 19:50 UTC, found-it approved these changes, later dismissed

2023-09-14 19:50 UTC, found-it commented on fluent-plugin-out-http.yaml
> +    identifier: splunk/fluent-plugin-out-http
I think this should be `fluent-plugins-nersery/fluent-plugin-out-http` so the auto-updater can locate the repo on github

2023-09-14 19:52 UTC, cjohannsen81 reviewed
You are right. Pipeline failed because of that.

2023-09-14 20:36 UTC, found-it requested changes

2023-09-14 20:36 UTC, found-it commented on fluent-plugin-out-http.yaml
> +    identifier: fluent-plugins-nursery/fluent-plugin-out-http
Looks like it's defaulting to releases which the upstream repo doesn't have. Probably need to add this flag

```suggestion
    identifier: fluent-plugins-nursery/fluent-plugin-out-http
    use-tag: true
```

2023-09-14 20:39 UTC, found-it commented on fluent-plugin-out-http.yaml
> +      uri: https://github.com/fluent-plugins-nursery/fluent-plugin-out-http/archive/refs/tags/${{package.version}}.tar.gz
```suggestion
      uri: https://github.com/fluent-plugins-nursery/fluent-plugin-out-http/archive/refs/tags/${{package.version}}.tar.gz
      uri: https://github.com/fluent-plugins-nursery/fluent-plugin-out-http/archive/refs/tags/v${{package.version}}.tar.gz
```

2023-09-14 20:39 UTC, found-it commented on fluent-plugin-out-http.yaml
> +      uri: https://github.com/fluent-plugins-nursery/fluent-plugin-out-http/archive/refs/tags/${{package.version}}.tar.gz
I _think_ you need a `v` in front of the version here

2023-09-14 20:39 UTC, found-it commented on fluent-plugin-out-http.yaml
> +      uri: https://github.com/fluent-plugins-nursery/fluent-plugin-out-http/archive/refs/tags/${{package.version}}.tar.gz
That looks to be why the build is failing

2023-09-15 17:10 UTC, found-it approved these changes

2023-09-15 17:19 UTC, merged