add golangci-lint
wolfi-dev/os pull request #567
Opened 2023-02-11 21:14 UTC by developer-guy

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

PTAL @dlorenc @jirfag

2023-02-11 21:37 UTC, developer-guy commented
@jirfag, it looks like golangci-lint requires `go` to be installed onto the environment, am I right? I'm asking because I've added `go` as a runtime dep of the golangci-lint package in wolfi.

2023-02-12 13:26 UTC, dlorenc commented
> @jirfag, it looks like golangci-lint requires `go` to be installed onto the environment, am I right? I'm asking because I've added `go` as a runtime dep of the golangci-lint package in wolfi.

That sounds plausible, it probably shells out to go tools.

2023-02-12 14:25 UTC, ldez commented
Hello, yes golangci-lint requires Go and also `diff`.

FYI, it's useless to ping Denis: he has not been active on the project for several years.
I'm the current active core maintainer.

I recommend not pinging directly maintainers especially when you don't know the person, as this can be considered harassment. Remember that you are not alone to do that, and managing a popular OSS is already taking a lot of time.

2023-02-12 14:38 UTC, kaniini commented
I do not believe there is any intent to annoy any upstream maintainers, but rather a desire to make them aware of the intent to include their package in the distribution, and to solicit any opinions about that intention.

2023-02-12 15:16 UTC, ldez commented
Don't take me wrong, I just trying to explain a recurring problem, it is neither against a person nor a project nor this PR. There is no major problem here, I'm trying to explain this just to improve the sanity of OSS maintainers.

Just a quick demo of the problem with this PR: there 3 messages each of them is pinging Denis.
After the first one, he can decide to unsubscribe but as the other messages are still continuing to ping him, he is forced to follow the topic.

I'm sure there are no bad intentions here but it is bad behavior.
I'm also sure that you can understand what I mean here.

Sorry for the off-topic, I hope I answered the original question in my previous message.

2023-02-15 04:36 UTC, imjasonh commented on golangci-lint.yaml
> +      - go
Did we also need to include `diff`?

2023-02-15 04:36 UTC, imjasonh commented on Makefile
> +$(eval $(call build-package,golangci-lint,1.51.1-r0))
Pro-tip: I've found that you can avoid merge conflicts here if you put new packages randomly in the bottom ~5-10 lines, instead of the last line.

2023-02-17 19:27 UTC, imjasonh requested changes

2023-02-17 19:27 UTC, imjasonh commented on golangci-lint.yaml
> +      - go
It sounds like we should include `diff`.

2023-02-27 09:33 UTC, closed without merging