Add openvpn
wolfi-dev/os pull request #5684
Opened 2023-09-19 06:08 UTC by johnfosborneiii

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [X] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [X] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

Passes all unit testing with provided samples

2023-09-19 09:31 UTC, rawlingsj requested changes, later dismissed

2023-09-19 09:31 UTC, rawlingsj commented on openvpn/vendor/down.sh
Could we add a link to the source of these vendored files?  It helps to help maintain them if they change upstream.

2023-09-19 13:17 UTC, johnfosborneiii commented on openvpn/vendor/openvpn.initd
It's more of a placeholder, I can remove them for now

2023-09-19 13:18 UTC, johnfosborneiii commented on openvpn/vendor/down.sh
https://git.alpinelinux.org/aports/tree/main/openvpn/

2023-09-19 13:19 UTC, johnfosborneiii commented on openvpn/vendor/openvpn.initd
Should I just remove them from the main package and keep them in the subpackage?

2023-09-21 17:42 UTC, kaniini approved these changes

2023-09-21 17:53 UTC, merged