Update go to 1.19.3
wolfi-dev/os pull request #64
Opened 2022-11-01 18:47 UTC by luhring

Resolves CVE-2022-41716

2022-11-01 18:55 UTC, kaniini requested changes

2022-11-01 18:55 UTC, kaniini commented on go.yaml
> +    repositories:
This isn't needed and shouldn't be present.  Instead, use `gsutil -m rsync` to clone the repository locally.  I can add some helpers to the Makefile to help with this.

2022-11-01 19:41 UTC, kaniini approved these changes

2022-11-01 19:41 UTC, merged

2022-11-02 02:14 UTC, tuananh commented
@luhring off topic question but may i ask why is epoch set to 1?

2022-11-02 02:52 UTC, kaniini commented
Because go binaries are staticly linked, we have to rebuild them when Go receives security updates, so we increase the epoch to trigger a rebuild.

2022-11-02 03:01 UTC, tuananh commented
that seems like a bit of manual, error-prone process, maybe it's better to have a check in CI for if a package like `go` get updated? which print out error message like "trivy is staticly linked with go, because this PR updates go so you need to bump epoch for trivy too"

2022-11-02 03:23 UTC, kaniini commented
We use `dag` to handle this.  https://github.com/wolfi-dev/dag

2022-11-02 07:04 UTC, tuananh commented
This is nice. I saw there's a PR for it but it's closed? https://github.com/wolfi-dev/os/pull/19

2022-11-02 19:44 UTC, imjasonh commented
That work moved to https://github.com/wolfi-dev/dag -- there are a few goals of that tool:

1. visualization of the dependency graph, just to be able to tell what depends on what, track over time, etc.
2. execution of the graph when things change -- e.g., when `go` is rebuilt, know to update and rebuild `trivy`, etc.
3. execution of the graph remotely -- instead of having the build graph manually maintained in `Makefile`, have `dag` create a K8s pod that runs the necessary builds in order on cloud VMs. This will also help us support arm64 builds better.

If this is interesting feel free to take it for a spin, file issues, and ask questions. We can discuss in more detail in a future public community call as well.