add rekor-cli and rekor-server binaries
wolfi-dev/os pull request #699
Opened 2023-03-03 20:08 UTC by developer-guy

Fixes: 

Related: 

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] The package is available under an OSI-approved or FSF-approved license
- [ ] The version of the package is still receiving security updates

#### For security-related PRs

- [ ] The security fix is recorded in `annotations` and `secfixes`

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

PTAL @dlorenc

2023-03-04 20:05 UTC, kaniini requested changes

2023-03-04 20:05 UTC, kaniini commented on rekor-cli.yaml
> +      package: github.com/sigstore/rekor/cmd/rekor-cli@latest@v${{package.version}}
```suggestion
      package: github.com/sigstore/rekor/cmd/rekor-cli@v${{package.version}}
```

2023-03-04 20:05 UTC, kaniini commented on rekor-server.yaml
> +      package: github.com/sigstore/rekor/cmd/rekor-server@latest@v${{package.version}}
```suggestion
      package: github.com/sigstore/rekor/cmd/rekor-server@v${{package.version}}
```

2023-03-17 13:08 UTC, imjasonh approved these changes, later dismissed

2023-03-17 13:09 UTC, imjasonh approved these changes

2023-03-20 20:58 UTC, imjasonh approved these changes

2023-03-20 20:59 UTC, kaniini approved these changes

2023-03-20 20:59 UTC, merged