package: libnotify
wolfi-dev/os pull request #7073
Opened 2023-10-18 21:47 UTC by mesaglio

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [X] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [X] REQUIRED - The version of the package is still receiving security updates
- [X] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2023-10-20 22:30 UTC, ajayk requested changes

2023-10-20 22:30 UTC, ajayk commented on libnotify.yaml
> +    - aarch64
```suggestion
```

2023-10-20 22:45 UTC, mesaglio commented on libnotify.yaml
> +    - aarch64
Fixed!

2023-10-21 03:19 UTC, ajayk approved these changes

2023-10-21 03:22 UTC, merged