new pkg: cabextract
wolfi-dev/os pull request #7422
Opened 2023-10-26 03:57 UTC by tuananh

use case:
- some application use pdf rendering engine, which requires use of msttcorefonts, which then need cabextract to extract the fonts.

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

2023-10-26 04:11 UTC, tuananh commented
@ajayk im not sure what lint rule is failing here. Can you help?

2023-10-26 05:15 UTC, ajayk commented
> @ajayk im not sure what lint rule is failing here. Can you help?

Not sure what's happening here , I copied the changes from here https://github.com/wolfi-dev/os/pull/7423/files which I used as a test it fails here , but passes in the test

2024-01-07 20:28 UTC, rawlingsj requested changes
Hi @tuananh - it looks like we can switch this to get the sources direct from GitHub and also enable auto updates.  I'm happy to do that, I can push to your branch.

2024-01-07 20:28 UTC, rawlingsj commented on cabextract.yaml
> +      uri: https://www.cabextract.org.uk/cabextract-${{package.version}}.tar.gz
I think we can switch this to `git-checkout` https://github.com/kyz/libmspack

2024-01-07 20:28 UTC, rawlingsj commented on cabextract.yaml
> +  enabled: false
As the source is on GitHub we can track the tags https://github.com/kyz/libmspack/tags

2024-01-07 20:54 UTC, rawlingsj commented on cabextract.yaml
> +      uri: https://www.cabextract.org.uk/cabextract-${{package.version}}.tar.gz
hmm that didn't work as I suspect the upstream release is adding extra configure files.  Let's ignore this comment.

2024-01-07 20:56 UTC, rawlingsj approved these changes

2024-01-07 21:05 UTC, merged