Nack CVE-2023-24329 in Python 3.10.
wolfi-dev/os pull request #937
Opened 2023-03-31 22:59 UTC by dlorenc

This one is an interesting read. The cypython maintainers argue that this is not a security issue in Python itself, but could present vulnerabilities in libraries that use the function in an unsafe manner.

Fixes:

Related:

### Pre-review Checklist

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates

#### For security-related PRs

- [ ] The security fix is recorded in `annotations` and `secfixes`

#### For version bump PRs

- [ ] The `epoch` field is reset to 0
- [ ] Patch source: _patch source here_

2023-04-04 17:00 UTC, imjasonh commented
There appears to be some fairly active discussion on this (https://github.com/python/cpython/issues/102153), let's keep this un-NACKed for now and see where that ends up.

2023-04-04 17:45 UTC, luhring requested changes
Let's hold this from merging for now, and check back soon to see if there's been progress upstream. If there's no progress on the upstream discussion soon, I think this would be reasonable to NAK.

2023-04-14 14:04 UTC, luhring approved these changes, later dismissed
I think we can proceed with this now: we've waited a very reasonable amount of time but it looks like the upstream conversation isn't progressing meaningfully, unfortunately.

2023-04-14 14:39 UTC, luhring commented
@dlorenc Think we need to get those last two required CI checks to run somehow

2023-04-14 14:54 UTC, dlorenc commented
> @dlorenc Think we need to get those last two required CI checks to run somehow

I'll rebase and force push, thanks!

2023-04-14 14:55 UTC, luhring approved these changes

2023-04-14 15:14 UTC, merged